### ISSUE TITLE
Make storage permissions optional? (<API 29)

### ISSUE THREAD

**Issue by KanadeTachibana2** [fm-sys/snapdrop-android#126]
**Is your feature request related to a problem? Please describe.**

Currently, "Snapdrop" always asks you to prompt storage permissions to be able to work; with no option to have them optional.

**Describe the solution you'd like**

Working without prompting access to storage would be a neat feature.

**Describe alternatives you've considered**

I guess the only alternative at the moment is allowing these permissions.

**Additional context**

[NewPipe](https://github.com/TeamNewPipe/NewPipe) made these permissions optional in one of its latest releases (you can now download files without the need of allowing storage permissions), [Privacy Browser](https://f-droid.org/en/packages/com.stoutner.privacybrowser.standard/) went to the extreme of removing them in one of its latest releases (yes, it works just fine without them!) and [Last Launcher](https://f-droid.org/en/packages/io.github.subhamtyagi.lastlauncher/) also removed them (to import/export settings).

**Comment by fm-sys** [comment]
Isn't this already the case for devices >=Android 10? Only, if you select a different download folder than the `/downloads` save location, it is asked for folder permission.

This is handled that way by the storage library we use. But maybe @anggrayudi has further  insights/ideas if it will work without the general storage permission...?

**Comment by PoetAnderson1** [comment]
oh...?

in Android 9, after doing a fresh install of "Snapdrop" (the latest version, 1.8.0), it still asks you to enable storage [permissions](https://user-images.githubusercontent.com/85243826/128977177-498dd686-dc73-4d06-a015-999b4a75e878.png).

if I deny them, I get the error [STORAGE_PERMISSION_DENIED](https://user-images.githubusercontent.com/85243826/128977394-90a0bf68-072a-4620-aaec-4adfe8a41827.png) later, when trying to save a file.

and yes, the [save location](https://user-images.githubusercontent.com/85243826/128977569-0b9f0186-f760-4308-8870-8175ed976b04.png) it's in its default setting.

**Comment by fm-sys** [comment]
Yes, for Android 9 this is indeed the case. We can check what needs to be changed...

**Comment by PoetAnderson1** [comment]
hm... maybe this can help you with that.

[this](https://user-images.githubusercontent.com/85243826/128994662-e31ef58e-1b04-4902-a694-fee1e7bc9e52.png) is the option that "NewPipe" uses to not trigger the storage permissions.

even if you do select custom folders, it will still not trigger them.

it was added in this [release](https://github.com/TeamNewPipe/NewPipe/releases/tag/v0.21.6), with this [pull request](https://github.com/TeamNewPipe/NewPipe/pull/5415).

it would probaby be better if you tested the app on your own to see what I'm talking about... haha.

**Comment by anggrayudi** [comment]
If you @PoetAnderson1 look into this line:
* [`DownloadDialog#717`](https://github.com/TeamNewPipe/NewPipe/pull/5415/files#diff-a0819817a17906cb4c863a58cdda2e9f60628b3027219bf8e7dc23cceb56e3afR717)
* [`StoredFileHelper#484`](https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/java/org/schabi/newpipe/streams/io/StoredFileHelper.java#L484)

NewPipe app uses `Intent.ACTION_CREATE_DOCUMENT` which is equivalent to "save as", so no storage permission is required. Snapdrop actually can do the same thing. When the files have been downloaded into the temporary folder, ask the user to select the save location and the file name. Once the user selected the location, move the files from the temporary folder into the selected location. SimpleStorage already has this capability via `SimpleStorageHelper.createFile()`.

You @fm-sys can replace `edit_text_dialog.xml` with SAF's "save as" dialog:

![image](https://user-images.githubusercontent.com/12292380/129005662-a2508293-96ee-4d69-bcfd-3c80fdb181d1.png)

But `Intent.ACTION_CREATE_DOCUMENT` has a downside: Because the storage permission is not granted, then you have to request the save location to the user for each downloaded file. Let's say that the user downloaded 5 files, then she/he will be asked 5 times as well.

An advantage of requesting storage permission is we don't have to prompt the SAF's dialog for each individual file, so we can do automatic download.

**Comment by KanadeTachibana2** [comment]
maybe we can keep both methods... like "NewPipe" does.

the "Storage Access Framework" option is turned on by default in "NewPipe", but... it can be disabled. it's not mandatory.

![screen_20210916-092224](https://user-images.githubusercontent.com/85243826/133612101-c0bd3c4e-58f4-4da0-ba06-9885abf0e4f2.png)

![screen_20210916-092235](https://user-images.githubusercontent.com/85243826/133612150-9fc053fe-4813-43bd-a178-aa73836e9e09.png)

I honestly don't mind doing a few more taps in exchange of not granting storage permissions; but I do understand if people aren't comfortable with that.

so... maybe we can make it optional?

**Comment by anggrayudi** [comment]
Your @KanadeTachibana2 suggestion is not proper for this app's use case. Here's what NewPipe does:
1. User tap download for each videos.
2. Ask save location to the user for each video files.
2. User selects a location, and SAF will create a file with the provided URI.
3. NewPipe app begins to write the file.

It is ok for most use cases, because the download button is only available for each video page. That's why NewPipe can't download batch videos.

Whereas Snapdrop can't act like that. What this app does are:
1. Files are received, we don't know how many files are received. It can be 100 files.
2. If we use NewPipe's behavior, it will prompt 100 save location requests to the user. Very annoying. That's why we don't want to use `Intent.ACTION_CREATE_DOCUMENT`.

Different app has different purposes and use cases. NewPipe's solution can't be applied here.
