### ISSUE TITLE
Hotspot as WiFi conncetion

### ISSUE THREAD

**Issue by mubashir-rehman** [fm-sys/snapdrop-android#46]
I just installed the app and it says "Please verify that you are connected to a WiFi network". However, I have already enabled hotspot. It should use device hotspot instead of asking for another WiFi connection.

**Comment by fm-sys** [comment]
I didn't even know that using a mobile hotspot is possible with https://snapdrop.net/ at all. There's an API to check if tethering is enabled. If so, Snapdrop should pass the WiFi check, with additional information that the device uses mobile data (for set up the connection) and might not work on every device...

https://stackoverflow.com/a/20432036/13513639

**Comment by crok** [comment]
> I didn't even know that using a mobile hotspot is possible with https://snapdrop.net/ at all. There's an API to check if tethering is enabled. If so, Snapdrop should pass the WiFi check, with additional information that the device uses mobile data (for set up the connection) and might not work on every device...
> 

I think you didn't get the situation and the problem.
Imagine two phones with no router or AP involved, like you are in a picnic in the forest with your loved ones and you took some pictures you want to share with the others.
Device "A" activates WIFI hotspot, device "B" connects to this hotspot - so both are having a kind of WLAN (and actual IP) connectivity to the other.. no Internet involved, just the hotspot (phone "A" has no mobile network access, but it doesn't even matter).
So the two phones' owners are trying to share files via Snapdrop.. but the one that actually the hotspot AP reports that there's no WLAN connection at all so Snapdrop doesn't even start (although the other one says everything is fine since it has a WLAN connection to an AP, does not matter whether it is a hotspot or an infrastucture AP connection).
So, _this_ is the problem.. in this scenario (_tested_) Snapdrop does not pass the Wifi check and you can't use the Snapdrop app like a "WIFI direct share" app even though technically the networking between the phones is actually totally available (and for example a simple HTTP, WebDAV or FTP, SCP, SFTP, etc.. service could easily run between them). I guess this is what  @mubashir-rehman is trying to say.

**Comment by mubashir-rehman** [comment]
@crok thanks a lot for explaining it well. I usually use https://github.com/trebleshot/android but it doesn't support Apple devices and has slow development because of many reasons. Snap drop is versatile, but the only problem is dependence on snap drop server for validating devices.

**Comment by fm-sys** [comment]
See https://github.com/fm-sys/snapdrop-android/issues/48#issuecomment-817358647. There I posted a screenshot, how the first solution will look like. Feel free to suggest better ideas...
